name: PYG
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cxx-compiler
  - python=3.10
  - pytorch
  - numpy==1.26
  - pip:
    - torch_geometric
    - pandas
    - lightning
    - pytorch-lightning
    - tensorboard
    - jupyterlab
    - uproot
    - awkward
    - h5py
    - pylorentz
    - torch-hep==0.0.4
    - hydra-core
    - rich
    - onnx
    - onnxruntime
    - onnxscript
